name: Checks
on: [ 'push' ]
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            -   name: Set up repository
                uses: actions/checkout@v3
            -   name: Set up node
                uses: actions/setup-node@v1
                with:
                    node-version: 16
            -   name: Cache node_modules
                uses: actions/cache@v2
                with:
                    path: '**/node_modules'
                    key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            -   name: Install npm dependencies
                if: steps.npm-cache.outputs.cache-hit != 'true'
                run: npm ci
            -   name: Run build
                run: npm run build

    linting:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            -   name: Set up repository
                uses: actions/checkout@v3
            -   name: Set up node
                uses: actions/setup-node@v1
                with:
                    node-version: 16
            -   name: Cache node_modules
                uses: actions/cache@v2
                with:
                    path: '**/node_modules'
                    key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            -   name: Install npm dependencies
                if: steps.npm-cache.outputs.cache-hit != 'true'
                run: npm ci
            -   name: Run linting
                run: npm run lint


    testing:
        name: Test
        runs-on: ubuntu-latest
        steps:
            -   name: Set up repository
                uses: actions/checkout@v3
            -   name: Set up node
                uses: actions/setup-node@v1
                with:
                    node-version: 16
            -   name: Cache node_modules
                uses: actions/cache@v2
                with:
                    path: '**/node_modules'
                    key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            -   name: Install npm
                if: steps.npm-cache.outputs.cache-hit != 'true'
                run: npm ci
            -   name: Run testing
                run: npm run test
