name: Integration
on: [ 'push' ]
env:
    PLAYWRIGHT_VERSION: 1.44.1
jobs:
    nuxt:
        name: Nuxt
        runs-on: ubuntu-latest
        steps:
            -   name: Set up repository
                uses: actions/checkout@v3
            -   name: Set up node
                uses: actions/setup-node@v1
                with:
                    node-version: 18
            -   uses: pnpm/action-setup@v4
                with:
                    version: 9.2.0
            -   name: Cache node_modules
                uses: actions/cache@v2
                with:
                    path: '**/node_modules'
                    key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            -   name: Install dependencies
                if: steps.npm-cache.outputs.cache-hit != 'true'
                run: pnpm install
            -   name: Run build
                run: pnpm run build
            -   name: Install Playwright Browsers
                run: pnpm dlx playwright@$PLAYWRIGHT_VERSION install --with-deps
                working-directory: packages/e2e/setup
            -   name: Create Inkline + Nuxt app
                run: pnpm run e2e:create:nuxt
                working-directory: packages/e2e/setup
            -   name: Build Nuxt app
                run: pnpm run build
                working-directory: packages/e2e/nuxt
            -   name: Run Playwright tests
                run: pnpm run e2e:nuxt
                working-directory: packages/e2e/setup
            -   uses: actions/upload-artifact@v3
                if: always()
                with:
                    name: playwright-report
                    path: packages/e2e/nuxt/playwright-report/
                    retention-days: 30

    vite:
        name: Vite.js
        runs-on: ubuntu-latest
        steps:
            -   name: Set up repository
                uses: actions/checkout@v3
            -   name: Set up node
                uses: actions/setup-node@v1
                with:
                    node-version: 18
            -   uses: pnpm/action-setup@v4
                with:
                    version: 9.2.0
            -   name: Cache node_modules
                uses: actions/cache@v2
                with:
                    path: '**/node_modules'
                    key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            -   name: Install dependencies
                if: steps.npm-cache.outputs.cache-hit != 'true'
                run: pnpm install
            -   name: Run build
                run: pnpm run build
            -   name: Install Playwright Browsers
                run: pnpm dlx playwright@$PLAYWRIGHT_VERSION install --with-deps
                working-directory: packages/e2e/setup
            -   name: Create Inkline + Vite.js app
                run: pnpm run e2e:create:vite
                working-directory: packages/e2e/setup
            -   name: Build Vite app
                run: pnpm run build
                working-directory: packages/e2e/vite
            -   name: Run Playwright tests
                run: pnpm run e2e:vite
                working-directory: packages/e2e/setup
            -   uses: actions/upload-artifact@v3
                if: always()
                with:
                    name: playwright-report
                    path: packages/e2e/vite/playwright-report/
                    retention-days: 30



