name: Integration
on: [ 'push' ]
jobs:
    nuxt:
        name: Nuxt
        runs-on: ubuntu-latest
        steps:
            -   name: Set up repository
                uses: actions/checkout@v3
            -   name: Set up node
                uses: actions/setup-node@v1
                with:
                    node-version: 18
            -   name: Cache node_modules
                uses: actions/cache@v2
                with:
                    path: '**/node_modules'
                    key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            -   name: Install npm dependencies
                if: steps.npm-cache.outputs.cache-hit != 'true'
                run: npm install
            -   name: Install Playwright Browsers
                run: npx playwright install --with-deps
            -   name: Create Inkline + Nuxt app
                run: npm run integration:nuxt:create
            -   name: Build Nuxt app
                run: |
                    cd inkline-nuxt
                    npm run build
            -   name: Run Playwright tests
                run: npm run e2e:nuxt
            -   uses: actions/upload-artifact@v3
                if: always()
                with:
                    name: playwright-report
                    path: playwright-report/
                    retention-days: 30

    vite:
        name: Vite.js
        runs-on: ubuntu-latest
        steps:
            -   name: Set up repository
                uses: actions/checkout@v3
            -   name: Set up node
                uses: actions/setup-node@v1
                with:
                    node-version: 18
            -   name: Cache node_modules
                uses: actions/cache@v2
                with:
                    path: '**/node_modules'
                    key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            -   name: Install npm dependencies
                if: steps.npm-cache.outputs.cache-hit != 'true'
                run: npm install
            -   name: Install Playwright Browsers
                run: npx playwright install --with-deps
            -   name: Create Inkline + Vite.js app
                run: npm run integration:vite:create
            -   name: Build Nuxt app
                run: |
                    cd inkline-vite
                    npm run build
            -   name: Run Playwright tests
                run: npm run e2e:vite
            -   uses: actions/upload-artifact@v3
                if: always()
                with:
                    name: playwright-report
                    path: playwright-report/
                    retention-days: 30



